name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev \
            gawk git gettext libssl-dev wget zstd

      - name: Download ImmortalWrt ImageBuilder
        run: |
          BUILD_URL="https://downloads.immortalwrt.org/snapshots/targets/armsr/armv8/immortalwrt-imagebuilder-armsr-armv8.Linux-x86_64.tar.zst"
          wget $BUILD_URL
          zstd -d immortalwrt-imagebuilder-*.tar.zst
          tar -xf immortalwrt-imagebuilder-*.tar
          rm -rf immortalwrt-imagebuilder-*.tar
          rm -rf immortalwrt-imagebuilder-*.tar.zst
          mv immortalwrt-imagebuilder-* immortalwrt-imagebuilder

      - name: Prepare Custom Shell
        run: |
          cd immortalwrt-imagebuilder
          mkdir -p files/etc/uci-defaults
          cp -a ../.github/workflows/01-init-settings/. files/etc/uci-defaults/
          find files/etc/uci-defaults -type f -exec chmod +x {} \;

      - name: Download Custom Plugins
        run: |
          wget -O packages/luci-app-passwall2.apk \
            https://github.com/soapmancn/luci-app-passwall2/releases/download/main/luci-app-passwall2-25.9.24-r1.apk
          wget -O packages/luci-i18n-passwall2-zh-cn.apk \
            https://github.com/soapmancn/luci-app-passwall2/releases/download/main/luci-i18n-passwall2-zh-cn-25.266.57814.ef38d45.apk

      - name: Build Image
        run: |
          cd immortalwrt-imagebuilder
          make image PROFILE=generic \
          PACKAGES="luci luci-app-passwall2 luci-i18n-passwall2-zh-cn luci-i18n-package-manager-zh-cn luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn luci-i18n-ddns-go-zh-cn luci-app-ddns-go ddns-go luci-i18n-ddns-go-zh-cn openssh-sftp-server etherwake wireguard-tools kmod-wireguard luci-proto-wireguard kmod-nft-socket kmod-nft-tproxy sing-box hysteria" \
          FILES="files" \
          BIN_EXT=qcow2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-image
          path: immortalwrt-imagebuilder/bin/targets/armsr/armv8/*.qcow2.gz

